# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh4P0cR7CLSNLI58-6kr7jc8UAKdXcYN
"""

l=["surya","kumar","reddy"]
for i in l:
    if(i=="kumar"):
       continue
    print(i)
else:
    print("execute this")

list(range(-10,0))

list(range(0,20,2))

l=["sudh","kumar","krish","naik"]

len(l)

list(range(len(l)-1,-1,-1))

for i in range (len(l)-1,-1,-1):
    print(l[i])

l2 = [23,45,22,21,87,6,89,8,20]

list(range(0,len(l2),2))

for i in range(0,len(l2),2):
    print(l2[i])

t = (23,"spr",45,"efg")

list(range(0,len(t),2))

for i in range(0,len(t),2):
    print(t[i])

dict = {
    "sdf":[1,3,5,4]

}

"""project 2# New Section"""

name=input("Enter your name: ")
english_marks=int(input("Enter your English marks: "))
maths_marks=int(input("Enter your Maths marks: "))
science_marks=int(input("Enter your Science marks: "))
total_marks=english_marks+maths_marks+science_marks
percentage=(total_marks/300)*100
if percentage>=90:
    grade="A+"
elif percentage>=80:
    grade="A"
elif percentage>=70:
    grade="B+"
elif percentage>=60:
    grade="B"
elif percentage<60:
    grade="C"
else:
    grade="F"
print("percentage:",percentage)
print("grade:",grade)